In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:
# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]), tensor([[103., 119.],
         [ 56.,  70.],
         [ 56.,  70.],
         [119., 133.],
         [ 22.,  37.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [8]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[-0.4442, -0.1927, -0.4879],
        [ 0.1369,  0.0434, -0.4474]], requires_grad=True)
---------
Parameter containing:
tensor([-0.5540, -0.3103], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [9]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [10]:
# Import nn.functional
import torch.nn.functional as F

In [12]:
# Define loss function
loss_fn = F.mse_loss

In [13]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(19196.0801, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [14]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [15]:
# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(52.3521, grad_fn=<MseLossBackward>)


In [16]:
# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.3408,  71.9659],
        [ 79.3744,  96.0566],
        [123.2770, 140.7606],
        [ 28.0555,  46.3874],
        [ 92.8124, 105.5836],
        [ 58.3408,  71.9659],
        [ 79.3744,  96.0566],
        [123.2770, 140.7606],
        [ 28.0555,  46.3874],
        [ 92.8124, 105.5836],
        [ 58.3408,  71.9659],
        [ 79.3744,  96.0566],
        [123.2770, 140.7606],
        [ 28.0555,  46.3874],
        [ 92.8124, 105.5836]], grad_fn=<AddmmBackward>)

In [17]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [18]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(24.7941, grad_fn=<MseLossBackward>)


 Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
 Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [19]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [20]:
# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.35158722 0.68843931 0.40300899]
 [0.76770715 0.01620847 0.75656187]]
Biases:
[[0.08546137 0.64754741]
 [0.57952022 0.45420956]
 [0.48139885 0.38489816]
 [0.37735333 0.48239206]
 [0.3489767  0.07232818]
 [0.68120748 0.22197113]
 [0.09723736 0.56115964]
 [0.77656196 0.7864599 ]
 [0.29574284 0.71553062]
 [0.97438463 0.98435133]
 [0.83834011 0.40384739]
 [0.39193121 0.55300531]
 [0.08211381 0.66620635]
 [0.26995276 0.14309849]
 [0.18688263 0.71128735]]


In [21]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [22]:
# Generate predictions
preds = model(inputs)

In [23]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[ 89.20614895  90.3082974 ]
 [118.94919214 120.16186546]
 [146.69487617 113.22794379]
 [ 80.7534729  107.4782749 ]
 [118.90929821 107.55946577]
 [ 89.80189505  89.88272112]
 [118.46690928 120.26881554]
 [146.99003928 113.62950553]
 [ 80.67186241 107.71141347]
 [119.53470614 108.47148892]
 [ 89.95902768  90.06459738]
 [118.76160313 120.26066122]
 [146.29559112 113.50925198]
 [ 80.64607233 107.13898133]
 [118.74720414 108.19842495]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [24]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [25]:
# Compute loss
loss = mse(preds, targets)
print(loss)

2652.1978199362643


In [26]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[6156.47311766 5338.83283009 3504.78043079]
 [3178.91021625  959.76741323 1121.02978879]]
biases_grad:
[[ 4.42748653  2.70777299]
 [ 5.05989228  2.55491539]
 [ 3.69265016 -2.63627416]
 [ 7.83379639  9.39710332]
 [ 2.12123976 -1.52540456]
 [ 4.50691934  2.65102948]
 [ 4.9955879   2.56917541]
 [ 3.73200524 -2.5827326 ]
 [ 7.82291499  9.42818846]
 [ 2.20462749 -1.40380148]
 [ 4.52787036  2.67527965]
 [ 5.03488042  2.56808816]
 [ 3.63941215 -2.5987664 ]
 [ 7.81947631  9.35186418]
 [ 2.09962722 -1.44021001]]


Adjust weights

In [27]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [28]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.29002249 0.63505098 0.36796119]
 [0.73591805 0.00661079 0.74535158]]
Biases:
[[0.0854171  0.64752033]
 [0.57946962 0.45418401]
 [0.48136193 0.38492452]
 [0.377275   0.48229809]
 [0.34895549 0.07234343]
 [0.68116241 0.22194462]
 [0.0971874  0.56113395]
 [0.77652464 0.78648572]
 [0.29566461 0.71543634]
 [0.97436258 0.98436536]
 [0.83829483 0.40382064]
 [0.39188087 0.55297963]
 [0.08207741 0.66623234]
 [0.26987457 0.14300497]
 [0.18686164 0.71130175]]


In [29]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1899.1722853950332


In [30]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [31]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

15.754903474792425


In [32]:
# Print predictions
print(preds)

[[ 57.5306852   71.39081   ]
 [ 80.94316452 100.74585592]
 [120.80834472 130.91645995]
 [ 24.55645301  42.01039288]
 [ 97.40862976 116.10558243]
 [ 58.12627166  70.96534777]
 [ 80.46101089 100.85277734]
 [121.10342874 131.31791408]
 [ 24.47486439  42.24346897]
 [ 98.0338701  117.01736119]
 [ 58.28336219  71.14717529]
 [ 80.75562578 100.8446252 ]
 [120.40916667 131.19769276]
 [ 24.44908122  41.67119023]
 [ 97.24657912 116.74437039]]


In [33]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
